version: '3'

services:
  backend:
          container_name: backendproyadmin
          restart: always
          build: .
          ports:
                - "4100:4000"
          links:
                - mongo         
  
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
         - "27018:27017"